
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lima_user
      POSTGRES_PASSWORD: lima_password
      POSTGRES_DB: lima_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lima_user -d lima_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://lima_user:lima_password@db:5432/lima_db
      SECRET_KEY: ${SECRET_KEY:-changeme}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data: