"""create users table

Revision ID: 4e8ef15bf966
Revises: 
Create Date: 2025-04-25 12:07:39.370859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8ef15bf966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('greenfield', 'rooftop', 'shopping', name='tipoendereco'), nullable=False),
    sa.Column('iddetentora', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('nivel_acesso', sa.Enum('basico', 'intermediario', 'super_usuario', name='nivelacesso'), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('alteracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_alteracao', sa.Enum('adicao', 'modificacao', 'remocao', name='tipoalteracao'), nullable=False),
    sa.Column('detalhe', sa.String(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buscas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('info_adicional', sa.String(), nullable=True),
    sa.Column('data_busca', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugestoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_sugestao', sa.Enum('adicao', 'modificacao', 'remocao', name='tiposugestao'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', name='statussugestao'), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.Column('detalhe', sa.String(), nullable=True),
    sa.Column('data_sugestao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sugestoes')
    op.drop_table('buscas')
    op.drop_table('alteracoes')
    op.drop_table('usuarios')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
